FROM animcogn/face_recognition:gpu-nightly

RUN pip3 install fastapi uvicorn numpy sqlalchemy pillow loguru

WORKDIR /app
COPY face_api/ ./face_api
COPY faces.db .
CMD ["uvicorn", "face_api.main:app", "--host", "0.0.0.0", "--port", "80"]